# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ApproxiW <- function(WW, la, ordd) {
    .Call(`_ProbitSpatial_ApproxiW`, WW, la, ordd)
}

grad_SAR_UC_FG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SAR_UC_FG`, th, env)
}

grad_SAR_UC_AG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SAR_UC_AG`, th, env)
}

grad_SAR_UP_AG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SAR_UP_AG`, th, env)
}

grad_SAR_UP_FG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SAR_UP_FG`, th, env)
}

grad_SEM_UC_AG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SEM_UC_AG`, th, env)
}

grad_SEM_UC_FG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SEM_UC_FG`, th, env)
}

grad_SEM_UP_AG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SEM_UP_AG`, th, env)
}

grad_SEM_UP_FG <- function(th, env) {
    .Call(`_ProbitSpatial_grad_SEM_UP_FG`, th, env)
}

lik_SAR_UC_conditional <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SAR_UC_conditional`, th, env)
}

lik_SAR_UC <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SAR_UC`, th, env)
}

lik_SAR_UP_conditional <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SAR_UP_conditional`, th, env)
}

lik_SAR_UP <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SAR_UP`, th, env)
}

lik_SARAR_UC_conditional <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SARAR_UC_conditional`, th, env)
}

lik_SARAR_UC <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SARAR_UC`, th, env)
}

lik_SARAR_UP_conditional <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SARAR_UP_conditional`, th, env)
}

lik_SARAR_UP <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SARAR_UP`, th, env)
}

lik_SEM_UC_conditional <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SEM_UC_conditional`, th, env)
}

lik_SEM_UC <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SEM_UC`, th, env)
}

lik_SEM_UP_conditional <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SEM_UP_conditional`, th, env)
}

lik_SEM_UP <- function(th, env) {
    .Call(`_ProbitSpatial_lik_SEM_UP`, th, env)
}

